apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/prefab-faculty-438111-k7/locations/us-central1-a/clusters/dev-cluster
