apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
  annotations: {}
  labels: {}
description: prod
gke:
  cluster: projects/prefab-faculty-438111-k7/locations/us-central1-a/clusters/stage-cluster
